# Generated by Django 5.1.5 on 2025-02-19 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipmentlisting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(choices=[(0.5, '0.5 - Very Poor'), (1, '1 - Poor'), (1.5, '1.5 - Below Average'), (2, '2 - Fair'), (2.5, '2.5 - Slightly Fair'), (3, '3 - Good'), (3.5, '3.5 - Above Average'), (4, '4 - Very Good'), (4.5, '4.5 - Excellent'), (5, '5 - Outstanding')], decimal_places=1, max_digits=2)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='equipmentlisting.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('equipment', 'user')},
            },
        ),
    ]
