# Generated by Django 5.1.5 on 2025-02-10 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('user_type', models.CharField(choices=[('farmer', 'Farmer'), ('owner', 'Owner')], max_length=10)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('pan_document', models.FileField(blank=True, null=True, upload_to='documents/pan/')),
                ('aadhaar_document', models.FileField(blank=True, null=True, upload_to='documents/aadhaar/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
