# Generated by Django 5.1.5 on 2025-02-12 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aadhaar_number',
            field=models.CharField(blank=True, default='', max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Aadhaar number must be exactly 12 digits.', regex='^\\d{12}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pan_number',
            field=models.CharField(blank=True, default='', max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN number (e.g., ABCDE1234F).', regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15),
            preserve_default=False,
        ),
    ]
