# Generated by Django 5.1.5 on 2025-02-12 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('pin_code', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('sub_district', models.CharField(max_length=50)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('image1', models.ImageField(upload_to='equipment_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='equipment_images/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
