# Generated by Django 5.1.5 on 2025-02-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentlisting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
