# Generated by Django 5.1.5 on 2025-03-04 06:59

import bookings.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipmentlisting', '0002_equipment_average_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_string', models.CharField(max_length=10)),
                ('id_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_no', models.CharField(max_length=10, unique=True)),
                ('shipping_address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('rental_start_date', models.DateField()),
                ('rental_end_date', models.DateField()),
                ('amount_payable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_days', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='equipmentlisting.equipment')),
                ('equipment_owner', models.ForeignKey(default=bookings.models.Booking.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
